/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ags.pms.forms;

import com.ags.pms.models.Lecturer;
import com.ags.pms.models.Request;
import com.ags.pms.models.Role;
import com.ags.pms.models.User;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Genzoku
 */
public class LecturerForm extends javax.swing.JFrame {
    
    private Lecturer lecturer;
    
    public LecturerForm() {
        initComponents();
        try {
            this.lecturer = new Lecturer(2001, "Joshua", "11/01/1980", "joshua@lecturer.com", "josh_lecturer", "verySecurePasswordMate", Role.NONE);
        } catch (InvalidKeyException | NoSuchAlgorithmException | NoSuchPaddingException | IllegalBlockSizeException
        | BadPaddingException | InvalidAlgorithmParameterException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        populatePresentationsRequest(); // Call the method to populate presentations
    }
    /**
     * Creates new form MainFormBody
     */
    public LecturerForm(User user) {
        initComponents();   
        this.lecturer = (Lecturer) user; // Fixing the assignment of lecturer
        // You're getting the email, but not doing anything with it.
        // If you need it, consider storing it or using it elsewhere.
        // user.getEmail(); 
        populatePresentationsRequest(); // Call the method to populate presentations
    }

private void populatePresentationsRequest() {
    DefaultTableModel model = (DefaultTableModel) jTablePresentation.getModel();
  
    // Clear the table before populating it again to avoid duplicate entries
    model.setRowCount(0);
  
    ArrayList<Request> presentations = lecturer.viewPresentationRequests();
  
    for (int i = 0; i < presentations.size(); i++) {
        Object rowData[] = new Object[4]; // Moved declaration inside the loop
  
        rowData[0] = presentations.get(i).getId();  
        rowData[1] = presentations.get(i).getUser().getName();
        rowData[2] = presentations.get(i).getModule();
        rowData[3] = presentations.get(i).isApproved();
        
        model.addRow(rowData);
    }

    jTablePresentation.setFocusable(false);
    jTablePresentation.setRowSelectionAllowed(false);
    jTablePresentation.setCellSelectionEnabled(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelSide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelDragLeft = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        requestBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        viewSupviseeBtn = new javax.swing.JButton();
        availabelSlotsBtn = new javax.swing.JButton();
        confirmDataBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();
        assignSuperviseeBtn = new javax.swing.JButton();
        jPanelContents = new javax.swing.JPanel();
        jpanelDashboard = new javax.swing.JPanel();
        jPanelViewPresentation = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePresentation = new javax.swing.JTable();
        jPanelAvailableSlots = new javax.swing.JPanel();
        jPanelConfirmDate = new javax.swing.JPanel();
        jPanelViewSupervisee = new javax.swing.JPanel();
        jPanelReport = new javax.swing.JPanel();
        jPanelViewAssignSupervisee = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanelTitle.setBackground(new java.awt.Color(245, 246, 248));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTitle.setText("Project Management System");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelTitle)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitle)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelSide.setBackground(new java.awt.Color(83, 116, 240));
        jPanelSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelSide.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 266, -1, -1));

        jPanelDragLeft.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lecturer");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Male User_3.png"))); // NOI18N

        requestBtn.setBackground(new java.awt.Color(110, 139, 251));
        requestBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        requestBtn.setForeground(new java.awt.Color(0, 0, 0));
        requestBtn.setText("View Presentation Requests");
        requestBtn.setBorderPainted(false);
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        dashboardBtn.setBackground(new java.awt.Color(110, 139, 251));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 0));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDragLeftLayout = new javax.swing.GroupLayout(jPanelDragLeft);
        jPanelDragLeft.setLayout(jPanelDragLeftLayout);
        jPanelDragLeftLayout.setHorizontalGroup(
            jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDragLeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDragLeftLayout.setVerticalGroup(
            jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addGroup(jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSide.add(jPanelDragLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        viewSupviseeBtn.setBackground(new java.awt.Color(110, 139, 251));
        viewSupviseeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSupviseeBtn.setForeground(new java.awt.Color(0, 0, 0));
        viewSupviseeBtn.setText("View Supervisee List");
        viewSupviseeBtn.setBorderPainted(false);
        viewSupviseeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupviseeBtnActionPerformed(evt);
            }
        });
        jPanelSide.add(viewSupviseeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 333, 237, 37));

        availabelSlotsBtn.setBackground(new java.awt.Color(110, 139, 251));
        availabelSlotsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        availabelSlotsBtn.setForeground(new java.awt.Color(0, 0, 0));
        availabelSlotsBtn.setText("Available Slots");
        availabelSlotsBtn.setBorderPainted(false);
        availabelSlotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabelSlotsBtnActionPerformed(evt);
            }
        });
        jPanelSide.add(availabelSlotsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 237, 37));

        confirmDataBtn.setBackground(new java.awt.Color(110, 139, 251));
        confirmDataBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmDataBtn.setForeground(new java.awt.Color(0, 0, 0));
        confirmDataBtn.setText("Confirm Date and Slots");
        confirmDataBtn.setBorderPainted(false);
        confirmDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDataBtnActionPerformed(evt);
            }
        });
        jPanelSide.add(confirmDataBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 278, 240, 37));

        feedbackBtn.setBackground(new java.awt.Color(110, 139, 251));
        feedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feedbackBtn.setForeground(new java.awt.Color(0, 0, 0));
        feedbackBtn.setText("Report With Feedback");
        feedbackBtn.setBorderPainted(false);
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });
        jPanelSide.add(feedbackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 388, 237, 37));

        assignSuperviseeBtn.setBackground(new java.awt.Color(110, 139, 251));
        assignSuperviseeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        assignSuperviseeBtn.setForeground(new java.awt.Color(0, 0, 0));
        assignSuperviseeBtn.setText("View Assign Supervisee");
        assignSuperviseeBtn.setBorderPainted(false);
        assignSuperviseeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignSuperviseeBtnActionPerformed(evt);
            }
        });
        jPanelSide.add(assignSuperviseeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 447, 231, 37));

        jPanelContents.setBackground(new java.awt.Color(153, 153, 255));
        jPanelContents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelDashboard.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jpanelDashboardLayout = new javax.swing.GroupLayout(jpanelDashboard);
        jpanelDashboard.setLayout(jpanelDashboardLayout);
        jpanelDashboardLayout.setHorizontalGroup(
            jpanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpanelDashboardLayout.setVerticalGroup(
            jpanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jpanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        jPanelViewPresentation.setBackground(new java.awt.Color(204, 204, 255));
        jPanelViewPresentation.setPreferredSize(new java.awt.Dimension(800, 560));

        jTablePresentation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "User", "Module", "Approved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePresentation);
        if (jTablePresentation.getColumnModel().getColumnCount() > 0) {
            jTablePresentation.getColumnModel().getColumn(0).setResizable(false);
            jTablePresentation.getColumnModel().getColumn(1).setResizable(false);
            jTablePresentation.getColumnModel().getColumn(2).setResizable(false);
            jTablePresentation.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanelViewPresentationLayout = new javax.swing.GroupLayout(jPanelViewPresentation);
        jPanelViewPresentation.setLayout(jPanelViewPresentationLayout);
        jPanelViewPresentationLayout.setHorizontalGroup(
            jPanelViewPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewPresentationLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanelViewPresentationLayout.setVerticalGroup(
            jPanelViewPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewPresentationLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanelContents.add(jPanelViewPresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelAvailableSlots.setBackground(new java.awt.Color(204, 204, 255));
        jPanelAvailableSlots.setPreferredSize(new java.awt.Dimension(800, 560));

        javax.swing.GroupLayout jPanelAvailableSlotsLayout = new javax.swing.GroupLayout(jPanelAvailableSlots);
        jPanelAvailableSlots.setLayout(jPanelAvailableSlotsLayout);
        jPanelAvailableSlotsLayout.setHorizontalGroup(
            jPanelAvailableSlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelAvailableSlotsLayout.setVerticalGroup(
            jPanelAvailableSlotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jPanelAvailableSlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelConfirmDate.setBackground(new java.awt.Color(204, 204, 255));
        jPanelConfirmDate.setPreferredSize(new java.awt.Dimension(800, 560));

        javax.swing.GroupLayout jPanelConfirmDateLayout = new javax.swing.GroupLayout(jPanelConfirmDate);
        jPanelConfirmDate.setLayout(jPanelConfirmDateLayout);
        jPanelConfirmDateLayout.setHorizontalGroup(
            jPanelConfirmDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelConfirmDateLayout.setVerticalGroup(
            jPanelConfirmDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jPanelConfirmDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelViewSupervisee.setBackground(new java.awt.Color(204, 204, 255));
        jPanelViewSupervisee.setPreferredSize(new java.awt.Dimension(800, 560));

        javax.swing.GroupLayout jPanelViewSuperviseeLayout = new javax.swing.GroupLayout(jPanelViewSupervisee);
        jPanelViewSupervisee.setLayout(jPanelViewSuperviseeLayout);
        jPanelViewSuperviseeLayout.setHorizontalGroup(
            jPanelViewSuperviseeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelViewSuperviseeLayout.setVerticalGroup(
            jPanelViewSuperviseeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jPanelViewSupervisee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelReport.setBackground(new java.awt.Color(204, 204, 255));
        jPanelReport.setPreferredSize(new java.awt.Dimension(800, 560));

        javax.swing.GroupLayout jPanelReportLayout = new javax.swing.GroupLayout(jPanelReport);
        jPanelReport.setLayout(jPanelReportLayout);
        jPanelReportLayout.setHorizontalGroup(
            jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelReportLayout.setVerticalGroup(
            jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jPanelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelViewAssignSupervisee.setBackground(new java.awt.Color(204, 204, 255));
        jPanelViewAssignSupervisee.setPreferredSize(new java.awt.Dimension(800, 560));

        javax.swing.GroupLayout jPanelViewAssignSuperviseeLayout = new javax.swing.GroupLayout(jPanelViewAssignSupervisee);
        jPanelViewAssignSupervisee.setLayout(jPanelViewAssignSuperviseeLayout);
        jPanelViewAssignSuperviseeLayout.setHorizontalGroup(
            jPanelViewAssignSuperviseeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelViewAssignSuperviseeLayout.setVerticalGroup(
            jPanelViewAssignSuperviseeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelContents.add(jPanelViewAssignSupervisee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1065, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        jpanelDashboard.setVisible(false);
        jPanelViewPresentation.setVisible(true);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(false);

        if (jPanelViewPresentation.isVisible()) {
            jTablePresentation.setEnabled(true);
        }
        jTablePresentation.setEnabled(false);
    }//GEN-LAST:event_requestBtnActionPerformed

    private void viewSupviseeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupviseeBtnActionPerformed
         jpanelDashboard.setVisible(false);
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(true);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(false);

    }//GEN-LAST:event_viewSupviseeBtnActionPerformed

    private void availabelSlotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabelSlotsBtnActionPerformed
         jpanelDashboard.setVisible(false);
        
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(true);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(false);

    }//GEN-LAST:event_availabelSlotsBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        
        jpanelDashboard.setVisible(true);
        
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(false);

        
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void confirmDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDataBtnActionPerformed
         jpanelDashboard.setVisible(false);
        
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(true);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(false);

    }//GEN-LAST:event_confirmDataBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
         jpanelDashboard.setVisible(false);
        
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(true);
        jPanelViewAssignSupervisee.setVisible(false);

    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void assignSuperviseeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignSuperviseeBtnActionPerformed
        jpanelDashboard.setVisible(false);
        
        jPanelViewPresentation.setVisible(false);
        jPanelAvailableSlots.setVisible(false);
        jPanelConfirmDate.setVisible(false);
        jPanelViewSupervisee.setVisible(false);
        jPanelReport.setVisible(false);
        jPanelViewAssignSupervisee.setVisible(true);
    }//GEN-LAST:event_assignSuperviseeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LecturerForm mainFormBody = new LecturerForm();

                // setTheme(mainFormBody);
                
                mainFormBody.setVisible(true);    
            }
            
            

            // private void setTheme(JFrame frame) {
            //     SwingUtilities.invokeLater(new Runnable() {
            //         @Override
            //         public void run() {
            //             try {
            //                 UIManager.setLookAndFeel(new FlatLightLaf());
            //                 SwingUtilities.updateComponentTreeUI(frame);
            //             } catch (UnsupportedLookAndFeelException ex) {
            //                 Logger.getLogger(LecturerForm.class.getName()).log(Level.SEVERE, null, ex);
            //             }
            //         }
            //     });
            // }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignSuperviseeBtn;
    private javax.swing.JButton availabelSlotsBtn;
    private javax.swing.JButton confirmDataBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelAvailableSlots;
    private javax.swing.JPanel jPanelConfirmDate;
    private javax.swing.JPanel jPanelContents;
    private javax.swing.JPanel jPanelDragLeft;
    private javax.swing.JPanel jPanelReport;
    private javax.swing.JPanel jPanelSide;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelViewAssignSupervisee;
    private javax.swing.JPanel jPanelViewPresentation;
    private javax.swing.JPanel jPanelViewSupervisee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePresentation;
    private javax.swing.JPanel jpanelDashboard;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton viewSupviseeBtn;
    // End of variables declaration//GEN-END:variables
}
