/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ags.pms.forms;

import com.ags.pms.models.ProjectManager;
import com.ags.pms.models.User;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Genzoku
 */
public class ProjectManagerForm extends javax.swing.JFrame {

    private ProjectManager projectManager;
    
    public ProjectManagerForm() {
        initComponents();   
    }
    /**
     * Creates new form MainFormBody
     */
    public ProjectManagerForm(User user) {
        initComponents();   
        this.projectManager = (ProjectManager) user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelDragLeft = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        feedbackBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        availabelSlotsBtn = new javax.swing.JButton();
        viewSupviseeBtn = new javax.swing.JButton();
        viewSupviseeBtn1 = new javax.swing.JButton();
        viewSupviseeBtn2 = new javax.swing.JButton();
        viewSupviseeBtn3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitle.setBackground(new java.awt.Color(245, 246, 248));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTitle.setText("Project Management System");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelTitle)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitle)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(83, 116, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 567, -1, -1));

        jPanelDragLeft.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Project Mangaer");

        javax.swing.GroupLayout jPanelDragLeftLayout = new javax.swing.GroupLayout(jPanelDragLeft);
        jPanelDragLeft.setLayout(jPanelDragLeftLayout);
        jPanelDragLeftLayout.setHorizontalGroup(
            jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanelDragLeftLayout.setVerticalGroup(
            jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                .addGroup(jPanelDragLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanelDragLeftLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addGap(165, 165, 165))
        );

        jPanel2.add(jPanelDragLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 105));

        feedbackBtn.setBackground(new java.awt.Color(110, 139, 251));
        feedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feedbackBtn.setForeground(new java.awt.Color(0, 0, 0));
        feedbackBtn.setText("Report With Feedback");
        feedbackBtn.setBorderPainted(false);
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });
        jPanel2.add(feedbackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 237, 37));

        dashboardBtn.setBackground(new java.awt.Color(110, 139, 251));
        dashboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(0, 0, 0));
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 237, 37));

        requestBtn.setBackground(new java.awt.Color(110, 139, 251));
        requestBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        requestBtn.setForeground(new java.awt.Color(0, 0, 0));
        requestBtn.setText("View Presentation Requests");
        requestBtn.setBorderPainted(false);
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });
        jPanel2.add(requestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 237, 37));

        availabelSlotsBtn.setBackground(new java.awt.Color(110, 139, 251));
        availabelSlotsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        availabelSlotsBtn.setForeground(new java.awt.Color(0, 0, 0));
        availabelSlotsBtn.setText("Available Slots");
        availabelSlotsBtn.setBorderPainted(false);
        availabelSlotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabelSlotsBtnActionPerformed(evt);
            }
        });
        jPanel2.add(availabelSlotsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 237, 37));

        viewSupviseeBtn.setBackground(new java.awt.Color(110, 139, 251));
        viewSupviseeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSupviseeBtn.setForeground(new java.awt.Color(0, 0, 0));
        viewSupviseeBtn.setText("View Report Status");
        viewSupviseeBtn.setBorderPainted(false);
        viewSupviseeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupviseeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(viewSupviseeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 237, 37));

        viewSupviseeBtn1.setBackground(new java.awt.Color(110, 139, 251));
        viewSupviseeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSupviseeBtn1.setForeground(new java.awt.Color(0, 0, 0));
        viewSupviseeBtn1.setText("View Supervisee List");
        viewSupviseeBtn1.setBorderPainted(false);
        viewSupviseeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupviseeBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(viewSupviseeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 237, 37));

        viewSupviseeBtn2.setBackground(new java.awt.Color(110, 139, 251));
        viewSupviseeBtn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSupviseeBtn2.setForeground(new java.awt.Color(0, 0, 0));
        viewSupviseeBtn2.setText("Assign Assesment Type");
        viewSupviseeBtn2.setBorderPainted(false);
        viewSupviseeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupviseeBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(viewSupviseeBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 237, 37));

        viewSupviseeBtn3.setBackground(new java.awt.Color(110, 139, 251));
        viewSupviseeBtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSupviseeBtn3.setForeground(new java.awt.Color(0, 0, 0));
        viewSupviseeBtn3.setText("Assign PM Role");
        viewSupviseeBtn3.setBorderPainted(false);
        viewSupviseeBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupviseeBtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(viewSupviseeBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 237, 37));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
//
//        jpanelDashboard.setVisible(true);
//
//        jPanelViewPresentation.setVisible(false);
//        jPanelAvailableSlots.setVisible(false);
//        jPanelConfirmDate.setVisible(false);
//        jPanelViewSupervisee.setVisible(false);
//        jPanelReport.setVisible(false);
//        jPanelViewAssignSupervisee.setVisible(false);

    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
//        jpanelDashboard.setVisible(false);
//        jPanelViewPresentation.setVisible(true);
//        jPanelAvailableSlots.setVisible(false);
//        jPanelConfirmDate.setVisible(false);
//        jPanelViewSupervisee.setVisible(false);
//        jPanelReport.setVisible(false);
//        jPanelViewAssignSupervisee.setVisible(false);
//
//        if (jPanelViewPresentation.isVisible()) {
//            jTablePresentation.setEnabled(true);
//        }
//        jTablePresentation.setEnabled(false);
    }//GEN-LAST:event_requestBtnActionPerformed

    private void availabelSlotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabelSlotsBtnActionPerformed
//        jpanelDashboard.setVisible(false);
//
//        jPanelViewPresentation.setVisible(false);
//        jPanelAvailableSlots.setVisible(true);
//        jPanelConfirmDate.setVisible(false);
//        jPanelViewSupervisee.setVisible(false);
//        jPanelReport.setVisible(false);
//        jPanelViewAssignSupervisee.setVisible(false);
    }//GEN-LAST:event_availabelSlotsBtnActionPerformed

    private void viewSupviseeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupviseeBtnActionPerformed
//        jpanelDashboard.setVisible(false);
//        jPanelViewPresentation.setVisible(false);
//        jPanelAvailableSlots.setVisible(false);
//        jPanelConfirmDate.setVisible(false);
//        jPanelViewSupervisee.setVisible(true);
//        jPanelReport.setVisible(false);
//        jPanelViewAssignSupervisee.setVisible(false);
    }//GEN-LAST:event_viewSupviseeBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
//        jpanelDashboard.setVisible(false);
//
//        jPanelViewPresentation.setVisible(false);
//        jPanelAvailableSlots.setVisible(false);
//        jPanelConfirmDate.setVisible(false);
//        jPanelViewSupervisee.setVisible(false);
//        jPanelReport.setVisible(true);
//        jPanelViewAssignSupervisee.setVisible(false);
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void viewSupviseeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupviseeBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSupviseeBtn1ActionPerformed

    private void viewSupviseeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupviseeBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSupviseeBtn2ActionPerformed

    private void viewSupviseeBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupviseeBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSupviseeBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectManagerForm mainFormBody = new ProjectManagerForm();

                // setTheme(mainFormBody);
                
                mainFormBody.setVisible(true);    
            }

            // private void setTheme(JFrame frame) {
            //     SwingUtilities.invokeLater(new Runnable() {
            //         @Override
            //         public void run() {
            //             try {
            //                 UIManager.setLookAndFeel(new FlatLightLaf());
            //                 SwingUtilities.updateComponentTreeUI(frame);
            //             } catch (UnsupportedLookAndFeelException ex) {
            //                 Logger.getLogger(ProjectManager.class.getName()).log(Level.SEVERE, null, ex);
            //             }
            //         }
            //     });
            // }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availabelSlotsBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDragLeft;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton viewSupviseeBtn;
    private javax.swing.JButton viewSupviseeBtn1;
    private javax.swing.JButton viewSupviseeBtn2;
    private javax.swing.JButton viewSupviseeBtn3;
    // End of variables declaration//GEN-END:variables
}
